# Generated by Django 5.2.5 on 2026-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organization_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='is_female_led',
            new_name='women_led',
        ),
        migrations.AlterField(
            model_name='facility',
            name='org_type',
            field=models.CharField(blank=True, choices=[('International NGO', 'International NGO'), ('Local NGO', 'Local NGO'), ('Community Based Org', 'Community-Based Org'), ('Coalition', 'Coalition'), ('Network', 'Network'), ('Other', 'Other')], max_length=50, verbose_name='Type of Organization'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='registration_status',
            field=models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Informal', 'Informal')], max_length=10, verbose_name='Registration Status'),
        ),
    ]
