# Generated by Django 5.2.5 on 2026-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_is_female_led_facility_women_led_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='persons_reached',
        ),
        migrations.AddField(
            model_name='facility',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Achievements objectives and Key impact areas'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='funding_source',
            field=models.CharField(blank=True, choices=[('Local', 'Local (≥50%)'), ('Foreign', 'Foreign (≥50%)'), ('Mixed', 'Mixed')], max_length=10, verbose_name='Main Funding Sources'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='youth_type',
            field=models.CharField(blank=True, choices=[('Youth-led', 'Youth-led'), ('Youth-serving', 'Youth-serving'), ('Youth-led & Youth-serving', 'Youth-led & Youth-serving')], max_length=60, verbose_name='Youth Type'),
        ),
    ]
