# Generated by Django 5.2.5 on 2026-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_facility_achievements_remove_facility_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='women_led',
        ),
        migrations.AddField(
            model_name='facility',
            name='is_women_led',
            field=models.BooleanField(null=True, verbose_name='Women-led?'),
        ),
    ]
