# Generated by Django 5.2.5 on 2026-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_facility_women_led_facility_is_women_led'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='youth_type',
            field=models.CharField(blank=True, choices=[('Youth-led', 'Youth-led'), ('Youth-serving', 'Youth-serving'), ('Youth-led & Youth-serving', 'Youth-led & Youth-serving')], max_length=60, null=True, verbose_name='Youth Type'),
        ),
    ]
