# Generated by Django 5.2.5 on 2026-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_facility_youth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address'),
        ),
    ]
