# Generated by Django 5.2.5 on 2026-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
