# Generated by Django 5.2.5 on 2026-04-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resources_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_county', models.CharField(max_length=255)),
                ('strategic_objective', models.CharField(max_length=255)),
                ('strategic_area', models.CharField(max_length=255)),
                ('strategic_action', models.CharField(max_length=255)),
                ('activity', models.TextField()),
                ('target_population', models.CharField(max_length=255)),
                ('numbers_reached', models.IntegerField(default=0)),
                ('level_of_implementation', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=50)),
                ('period', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overall_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
