# Generated by Django 5.2.5 on 2026-04-06 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='org_type',
            field=models.CharField(blank=True, choices=[('International NGO', 'International NGO'), ('Local NGO', 'Local NGO'), ('Public', 'Public'), ('Private', 'Private'), ('Community Based Org', 'Community-Based Org'), ('Coalition', 'Coalition'), ('Network', 'Network'), ('Other', 'Other')], max_length=50, verbose_name='Type of Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hear_about_us',
            field=models.CharField(choices=[('internet', 'Internet Search'), ('social', 'Social Media'), ('direct', 'Direct Mail or Physical Advertisement'), ('referral', 'Referral'), ('news', 'News Article'), ('event', 'Event or Conference'), ('opds', 'Our organization is already part of OPDs'), ('forum', 'Heard about the platform during a forum'), ('other', 'Other')], default='referral', max_length=20, verbose_name='How did you hear about us?'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
